modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="mine_chatcorrect"
version="0.1.0"
displayName="Mine-ChatCorrect"
authors="Kaiki"
description='''Client-side chat spell checking for Minecraft NeoForge.'''

[[mixins]]
config="mine_chatcorrect.mixins.json"

[[dependencies.mine_chatcorrect]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.mine_chatcorrect]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"